// Code generated by ObjectBox; DO NOT EDIT.

#pragma once

#ifdef __cplusplus
#include <cstdbool>
#include <cstdint>
extern "C" {
#else
#include <stdbool.h>
#include <stdint.h>
#endif
#include "objectbox.h"

/// Initializes an ObjectBox model for all entities. 
/// The returned pointer may be NULL if the allocation failed. If the returned model is not NULL, you should check if   
/// any error occurred by calling obx_model_error_code() and/or obx_model_error_message(). If an error occurred, you're
/// responsible for freeing the resources by calling obx_model_free().
/// In case there was no error when setting the model up (i.e. obx_model_error_code() returned 0), you may configure 
/// OBX_store_options with the model by calling obx_opt_model() and subsequently opening a store with obx_store_open().
/// As soon as you call obx_store_open(), the model pointer is consumed and MUST NOT be freed manually.
static inline OBX_model* create_obx_model() {
    OBX_model* model = obx_model();
    if (!model) return NULL;
    
    obx_model_entity(model, "Dir", 1, 5273310822014120538);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 8781864133527138579);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "child_dirs", OBXPropertyType_Relation, 2, 6485923409973433079);
    obx_model_property_flags(model, (OBXPropertyFlags) (OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO));
    obx_model_property_relation(model, "Dir", 1, 3674306967133091017);
    obx_model_property(model, "child_files", OBXPropertyType_Relation, 3, 8910054242339236288);
    obx_model_property_flags(model, (OBXPropertyFlags) (OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO));
    obx_model_property_relation(model, "File", 2, 3084899737278824049);
    obx_model_entity_last_property_id(model, 3, 8910054242339236288);
    
    obx_model_entity(model, "File", 2, 6611680674991512449);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 5836909812952743470);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "filename", OBXPropertyType_String, 2, 7866595881051383089);
    obx_model_property(model, "content", OBXPropertyType_String, 3, 2693003018613535851);
    obx_model_entity_last_property_id(model, 3, 2693003018613535851);
    
    obx_model_last_entity_id(model, 2, 6611680674991512449);
    obx_model_last_index_id(model, 2, 3084899737278824049);
    return model; // NOTE: the returned model will contain error information if an error occurred.
}

#ifdef __cplusplus
}
#endif
