#! /usr/bin/python3

from sys import argv
from pathlib import Path
import shutil


class FileUtils():
    @staticmethod
    def copy(origin: Path, dest: Path):
        assert not dest.is_file()
        assert origin.exists()

        if dest.exists() and dest.is_dir():
            dest = dest / origin.name

        shutil.copytree(origin, dest)


if __name__ == "__main__":
    origin = Path(argv[1])
    dest   = Path(argv[2])

    FileUtils.copy(origin, dest)
